// <auto-generated />
using System;
using Egost.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Egost.Migrations
{
    [DbContext(typeof(EgostContext))]
    [Migration("20240821121201_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Egost.Areas.Identity.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Egost.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StoreAddress")
                        .HasColumnType("bit");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "Base",
                            AddressLine2 = "",
                            City = "Base",
                            Country = "Base",
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7742),
                            PostalCode = "Base",
                            StoreAddress = true,
                            Telephone = "Base"
                        });
                });

            modelBuilder.Entity("Egost.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromoCodeId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Egost.Models.CartProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("Egost.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sports, Instruments & Accessories"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toys, Games, Video Games & Accessories"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Arts, Crafts & Sewing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Clothing, Shoes & Jewelry"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Electronics & Accessories"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Software"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Grocery & Gourmet Food"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Home Furniture & Accessories"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Luggage & Travel Gear"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Pet Supplies"
                        });
                });

            modelBuilder.Entity("Egost.Models.EditHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EditDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("EditorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("ReviewId");

                    b.ToTable("EditHistories");
                });

            modelBuilder.Entity("Egost.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeliveryNeeded")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaymobOrderId")
                        .HasColumnType("int");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<int?>("PromoCodeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCents")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("TransporterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("TransporterId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Egost.Models.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PartiallyOrFullyReturnedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductPriceCents")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<float>("SalePercent")
                        .HasColumnType("real");

                    b.Property<TimeSpan>("Warranty")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Egost.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceCents")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("SKU")
                        .HasColumnType("bigint");

                    b.Property<int>("SalePercent")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Warranty")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7980),
                            Description = "High-quality tennis racket for professionals.",
                            Name = "Wilson Tennis Racket",
                            PriceCents = 8999m,
                            SKU = 10001L,
                            SalePercent = 10,
                            Warranty = new TimeSpan(730, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7983),
                            Description = "Top-notch acoustic guitar with a smooth finish.",
                            Name = "Yamaha Acoustic Guitar",
                            PriceCents = 14999m,
                            SKU = 10002L,
                            SalePercent = 15,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7987),
                            Description = "Latest EA sports soccer game ps5 edition.",
                            Name = "EA sports FC24 for PS5",
                            PriceCents = 12999m,
                            SKU = 10003L,
                            SalePercent = 5,
                            Warranty = new TimeSpan(14, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7989),
                            Description = "Official size soccer ball for all levels.",
                            Name = "Adidas Soccer Ball",
                            PriceCents = 2999m,
                            SKU = 10004L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7992),
                            Description = "Complete badminton set for backyard fun.",
                            Name = "Wilson Badminton Set",
                            PriceCents = 4599m,
                            SKU = 10005L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7996),
                            Description = "Buildable Star Wars-themed LEGO set.",
                            Name = "LEGO Star Wars Set",
                            PriceCents = 7999m,
                            SKU = 20001L,
                            SalePercent = 5,
                            Warranty = new TimeSpan(183, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(7999),
                            Description = "Next-generation gaming console with ultra-high-speed SSD.",
                            Name = "PlayStation 5 Console",
                            PriceCents = 49999m,
                            SKU = 20002L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8001),
                            Description = "Powerful gaming console with immersive gameplay.",
                            Name = "Xbox Series X",
                            PriceCents = 49999m,
                            SKU = 20003L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8004),
                            Description = "Portable gaming console for versatile play.",
                            Name = "Nintendo Switch",
                            PriceCents = 29999m,
                            SKU = 20004L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8007),
                            Description = "Classic board game for family and friends.",
                            Name = "Hasbro Monopoly Game",
                            PriceCents = 1999m,
                            SKU = 20005L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8010),
                            Description = "Reliable sewing machine for all skill levels.",
                            Name = "Singer Sewing Machine",
                            PriceCents = 15999m,
                            SKU = 30001L,
                            SalePercent = 20,
                            Warranty = new TimeSpan(1095, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8012),
                            Description = "Versatile cutting machine for crafting projects.",
                            Name = "Cricut Maker Machine",
                            PriceCents = 39999m,
                            SKU = 30002L,
                            SalePercent = 10,
                            Warranty = new TimeSpan(730, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8015),
                            Description = "High-quality colored pencils for artists.",
                            Name = "Faber-Castell Colored Pencils",
                            PriceCents = 2499m,
                            SKU = 30003L,
                            SalePercent = 5,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8018),
                            Description = "Alcohol-based markers for smooth blending.",
                            Name = "Prismacolor Markers",
                            PriceCents = 3999m,
                            SKU = 30004L,
                            SalePercent = 10,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8021),
                            Description = "Premium watercolor paints for artists.",
                            Name = "Schmincke Watercolors",
                            PriceCents = 5999m,
                            SKU = 30005L,
                            SalePercent = 5,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8023),
                            Description = "Classic straight-fit jeans for men.",
                            Name = "Levi's Denim Jeans",
                            PriceCents = 4999m,
                            SKU = 40001L,
                            SalePercent = 10,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8026),
                            Description = "Comfortable and stylish sneakers for daily wear.",
                            Name = "Nike Air Max Sneakers",
                            PriceCents = 8999m,
                            SKU = 40002L,
                            SalePercent = 15,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8029),
                            Description = "Soft cotton T-shirt with modern fit.",
                            Name = "Calvin Klein T-shirt",
                            PriceCents = 1999m,
                            SKU = 40003L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8032),
                            Description = "Iconic sunglasses with a timeless design.",
                            Name = "Ray-Ban Aviator Sunglasses",
                            PriceCents = 14999m,
                            SKU = 40004L,
                            SalePercent = 10,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8035),
                            Description = "Luxury leather handbag with modern style.",
                            Name = "Michael Kors Leather Handbag",
                            PriceCents = 29999m,
                            SKU = 40005L,
                            SalePercent = 5,
                            Warranty = new TimeSpan(730, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8037),
                            Description = "Powerful hair dryer with multiple heat settings.",
                            Name = "Revlon Hair Dryer",
                            PriceCents = 3999m,
                            SKU = 50001L,
                            SalePercent = 10,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8040),
                            Description = "Anti-aging cream for daily use.",
                            Name = "Olay Regenerist Cream",
                            PriceCents = 2999m,
                            SKU = 50002L,
                            SalePercent = 5,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8043),
                            Description = "Cordless electric shaver with precision blades.",
                            Name = "Philips Electric Shaver",
                            PriceCents = 7999m,
                            SKU = 50003L,
                            SalePercent = 15,
                            Warranty = new TimeSpan(730, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8045),
                            Description = "Rechargeable toothbrush with multiple brush heads.",
                            Name = "Oral-B Electric Toothbrush",
                            PriceCents = 5999m,
                            SKU = 50004L,
                            SalePercent = 10,
                            Warranty = new TimeSpan(730, 0, 0, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8048),
                            Description = "Moisturizing body wash for soft skin.",
                            Name = "Dove Body Wash",
                            PriceCents = 1299m,
                            SKU = 50005L,
                            SalePercent = 0,
                            Warranty = new TimeSpan(365, 0, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Egost.Models.PromoCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxSaleCents")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Percent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PromoCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Code = "SUMMER2024",
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8083),
                            Description = "SUMMER2024",
                            MaxSaleCents = 5000m,
                            Percent = 10
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Code = "WELCOME10",
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8086),
                            Description = "WELCOME10",
                            Percent = 10
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Code = "HOLIDAY25",
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8089),
                            Description = "HOLIDAY25",
                            MaxSaleCents = 15000m,
                            Percent = 25
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Code = "SPRING2024",
                            CreatedDateTime = new DateTime(2024, 8, 21, 15, 12, 1, 29, DateTimeKind.Local).AddTicks(8123),
                            Description = "SPRING2024",
                            MaxSaleCents = 8000m,
                            Percent = 15
                        });
                });

            modelBuilder.Entity("Egost.Models.ReturnProductOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderProductId")
                        .HasColumnType("int");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("ReturnReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransporterId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderProductId");

                    b.HasIndex("TransporterId");

                    b.ToTable("ReturnProductOrders");
                });

            modelBuilder.Entity("Egost.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte>("Rate")
                        .HasColumnType("tinyint");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Egost.Models.Search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("KeyWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Searches");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.Property<int>("WishListId")
                        .HasColumnType("int");

                    b.Property<string>("WishlistUsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WishListId", "WishlistUsersId");

                    b.HasIndex("WishlistUsersId");

                    b.ToTable("ProductUser");
                });

            modelBuilder.Entity("Egost.Areas.Identity.Data.User", b =>
                {
                    b.HasOne("Egost.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Egost.Models.Address", b =>
                {
                    b.HasOne("Egost.Areas.Identity.Data.User", null)
                        .WithMany("Addresses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Egost.Models.Cart", b =>
                {
                    b.HasOne("Egost.Models.PromoCode", "PromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId");

                    b.Navigation("PromoCode");
                });

            modelBuilder.Entity("Egost.Models.CartProduct", b =>
                {
                    b.HasOne("Egost.Models.Cart", null)
                        .WithMany("CartProducts")
                        .HasForeignKey("CartId");

                    b.HasOne("Egost.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Egost.Models.EditHistory", b =>
                {
                    b.HasOne("Egost.Models.Address", null)
                        .WithMany("EditsHistory")
                        .HasForeignKey("AddressId");

                    b.HasOne("Egost.Areas.Identity.Data.User", "Editor")
                        .WithMany("EditsHistory")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egost.Models.Product", null)
                        .WithMany("EditsHistory")
                        .HasForeignKey("ProductId");

                    b.HasOne("Egost.Models.PromoCode", null)
                        .WithMany("EditsHistory")
                        .HasForeignKey("PromoCodeId");

                    b.HasOne("Egost.Models.Review", null)
                        .WithMany("EditsHistory")
                        .HasForeignKey("ReviewId");

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("Egost.Models.Order", b =>
                {
                    b.HasOne("Egost.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egost.Models.PromoCode", "PromoCode")
                        .WithMany()
                        .HasForeignKey("PromoCodeId");

                    b.HasOne("Egost.Areas.Identity.Data.User", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Egost.Areas.Identity.Data.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("PromoCode");

                    b.Navigation("Transporter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Egost.Models.OrderProduct", b =>
                {
                    b.HasOne("Egost.Models.Order", null)
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId");

                    b.HasOne("Egost.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Egost.Models.Product", b =>
                {
                    b.HasOne("Egost.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Egost.Models.ReturnProductOrder", b =>
                {
                    b.HasOne("Egost.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egost.Models.OrderProduct", "OrderProduct")
                        .WithMany()
                        .HasForeignKey("OrderProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egost.Areas.Identity.Data.User", "Transporter")
                        .WithMany()
                        .HasForeignKey("TransporterId");

                    b.Navigation("Order");

                    b.Navigation("OrderProduct");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("Egost.Models.Review", b =>
                {
                    b.HasOne("Egost.Models.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId");

                    b.HasOne("Egost.Areas.Identity.Data.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Egost.Models.Search", b =>
                {
                    b.HasOne("Egost.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Egost.Areas.Identity.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Egost.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Egost.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egost.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Egost.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductUser", b =>
                {
                    b.HasOne("Egost.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Egost.Areas.Identity.Data.User", null)
                        .WithMany()
                        .HasForeignKey("WishlistUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Egost.Areas.Identity.Data.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("EditsHistory");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Egost.Models.Address", b =>
                {
                    b.Navigation("EditsHistory");
                });

            modelBuilder.Entity("Egost.Models.Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("Egost.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Egost.Models.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("Egost.Models.Product", b =>
                {
                    b.Navigation("EditsHistory");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Egost.Models.PromoCode", b =>
                {
                    b.Navigation("EditsHistory");
                });

            modelBuilder.Entity("Egost.Models.Review", b =>
                {
                    b.Navigation("EditsHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
